#!/bin/sh

uci set network.lan.ipaddr='192.168.3.249'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.3.254'
uci -q delete network.lan.dns
uci add_list network.lan.dns='192.168.3.254'
uci add_list network.lan.dns='223.5.5.5'
uci set network.lan.delegate='0'
uci commit network

uci set dropbear.main.enable='1'
uci set dropbear.main.PasswordAuth='on'
uci set dropbear.main.RootPasswordAuth='on'
uci set dropbear.main.Port='9167'
uci set dropbear.main.Interface='lan'
uci commit dropbear

printf '%s\n%s\n' '123456..' '123456..' | passwd root

/etc/init.d/network restart
/etc/init.d/dropbear restart

exit 0
